### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'Utc'

### ISSUE THREAD

**Issue by batmanscode** [woluxwolu/twint#5]
Not sure whether this is due to the archiving. Are you able to still get results?

**Comment by joshrayman** [comment]
I had this problem too. Fixed it by adding this to my config:
```
c = twint.Config()

c.Utc = True
c.Full_text = True
```
Looks like this merge added additional mandantory config params - 
https://github.com/woluxwolu/twint/commit/6a49f32f9d073d143439890bb64bb4717335d1f5

**Comment by batmanscode** [comment]
Thank you @joshrayman! Looks like that'll work

Do you know what `full_text` does?

**Comment by rohanch398** [comment]
Thank you @joshrayman! Worked for me! <3
